services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: notes-app
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/notesdb
    restart: unless-stopped
  db:
    image: mongo:latest
    container_name: notes-db
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data:
